### ISSUE TITLE
mikrotik_enforce_dns_block_doh + AdGuard Home

### ISSUE THREAD

**Issue by vdias** [ncravino/mikrotik_enforce_dns_block_doh#1]
Like your approach, but how could we do this adding a Adguard Home to the equation?

Router: 192.168.100.1
AdGuard Home: 192.168.200.2

Idea:
- Router using ISP default DNS server
- Adguard Home using some DOH dns servers
- Permit the adguard home to use DOH freely
- Redirect all TCP/UDP DNS requests to a address list that contains 192.168.200.1 and 192.168.200.2, in case Adguard Home is down it just fall down to the router with the default ISP DNS
- Blocking all DoH requests from LAN using the firewall rule and address list

Do you think that this posible?

**Comment by ncravino** [comment]
I've no experience with AdGuard however I do use DoH, I just whitelist (don't block) the specific server I use.
